# Generated by Django 5.1.5 on 2025-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_orderitem_user_order_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon_code",
            name="discount",
            field=models.FloatField(),
        ),
    ]
