# Generated by Django 5.1.5 on 2025-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_vendor_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="availability",
            field=models.IntegerField(null=True),
        ),
    ]
