# Generated by Django 5.1.5 on 2025-01-23 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_product_availability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="created_at",
        ),
    ]
