# Generated by Django 5.1.5 on 2025-01-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_brand_created_at_brand_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.brand",
            ),
        ),
    ]
