# Generated by Django 5.1.5 on 2025-02-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(upload_to="media/product_imgs"),
        ),
    ]
