# Generated by Django 5.1.5 on 2025-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_product_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_image",
            name="image",
            field=models.ImageField(upload_to="media/product_imgs"),
        ),
    ]
