# Generated by Django 5.1.5 on 2025-02-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_category_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                null=True, related_name="products", to="app.color"
            ),
        ),
    ]
