# Generated by Django 5.1.5 on 2025-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_color_name_remove_product_color_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="colors",
            field=models.ManyToManyField(
                blank=True, related_name="cart_items", to="app.color"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.ManyToManyField(
                blank=True, related_name="order_items", to="app.color"
            ),
        ),
    ]
