# Generated by Django 5.1.5 on 2025-02-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_productcolor_cart_product_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product_color",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_color",
        ),
    ]
