# Generated by Django 5.1.5 on 2025-02-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_remove_product_sizes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Size",
        ),
    ]
