# Generated by Django 5.1.5 on 2025-02-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_productvariant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
