# Generated by Django 5.1.5 on 2025-02-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_delete_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="orders", to="app.vendor"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="app.vendor",
            ),
        ),
    ]
