# Generated by Django 5.1.5 on 2025-02-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_productvariation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariation",
            unique_together={("product", "size", "color")},
        ),
    ]
