# Generated by Django 5.1.5 on 2025-03-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_alter_productvariation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="variant",
            field=models.CharField(
                choices=[("None", "None"), ("Size", "Size")],
                default="None",
                max_length=10,
            ),
        ),
    ]
