# Generated by Django 5.1.5 on 2025-03-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="app.size"
            ),
        ),
    ]
