# Generated by Django 5.1.5 on 2025-03-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_product_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
    ]
