# Generated by Django 5.1.5 on 2025-03-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_remove_product_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
