# Generated by Django 5.1.5 on 2025-03-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_productvariation_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
