# Generated by Django 5.1.5 on 2025-03-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_orderitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="brand",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor",
                to="app.brand",
            ),
        ),
    ]
