# Generated by Django 5.1.5 on 2025-04-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/product_imgs"
            ),
        ),
    ]
