# Generated by Django 5.1.5 on 2025-04-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_alter_product_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="media/product_imgs"
            ),
        ),
    ]
