# Generated by Django 5.1.5 on 2025-04-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_alter_product_featured_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariation",
            unique_together=set(),
        ),
    ]
