# Generated by Django 5.1.5 on 2025-04-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_productvariation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="productvariation",
            unique_together={("product", "size")},
        ),
    ]
