# Generated by Django 5.1.5 on 2025-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_order_shipped_alter_productvariation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="model_name",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_information",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.CharField(max_length=900),
        ),
    ]
