# Generated by Django 5.1.5 on 2025-05-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_shippingzone_order_shipping_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_zone",
        ),
        migrations.DeleteModel(
            name="ShippingZone",
        ),
    ]
